[2024-11-01T18:21:24.734+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bluebikes_data_pipeline.upload_to_gcs_task scheduled__2024-09-01T00:00:00+00:00 [queued]>
[2024-11-01T18:21:24.777+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bluebikes_data_pipeline.upload_to_gcs_task scheduled__2024-09-01T00:00:00+00:00 [queued]>
[2024-11-01T18:21:24.779+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2024-11-01T18:21:24.956+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): upload_to_gcs_task> on 2024-09-01 00:00:00+00:00
[2024-11-01T18:21:25.022+0000] {standard_task_runner.py:57} INFO - Started process 322 to run task
[2024-11-01T18:21:25.118+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'bluebikes_data_pipeline', 'upload_to_gcs_task', 'scheduled__2024-09-01T00:00:00+00:00', '--job-id', '797', '--raw', '--subdir', 'DAGS_FOLDER/***_main.py', '--cfg-path', '/tmp/tmp54wva_ks']
[2024-11-01T18:21:25.137+0000] {standard_task_runner.py:85} INFO - Job 797: Subtask upload_to_gcs_task
[2024-11-01T18:21:25.981+0000] {task_command.py:410} INFO - Running <TaskInstance: bluebikes_data_pipeline.upload_to_gcs_task scheduled__2024-09-01T00:00:00+00:00 [running]> on host f1ce4a924b75
[2024-11-01T18:21:27.625+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Muskan' AIRFLOW_CTX_DAG_ID='bluebikes_data_pipeline' AIRFLOW_CTX_TASK_ID='upload_to_gcs_task' AIRFLOW_CTX_EXECUTION_DATE='2024-09-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-01T00:00:00+00:00'
[2024-11-01T18:21:52.952+0000] {logging_mixin.py:150} INFO - Error uploading /opt/***/extracted_files/202409-bluebikes-tripdata.csv: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /upload/storage/v1/b/blue_bikes_bucket/o?uploadType=resumable&upload_id=AHmUCY08ctXV8leNkKMdRxQa-YppYMTXulrQQ1OXngGObOG42ZlM9u34JiKYRtGpXzZ_yufm99SIFdf0ZrNuk-CLzSW0t1x3TNh7YMoZEp4rn87pJg (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_BAD_RECORD_MAC] sslv3 alert bad record mac (_ssl.c:2570)')))
[2024-11-01T18:24:06.033+0000] {logging_mixin.py:150} INFO - Error uploading /opt/***/extracted_files/202409-bluebikes-tripdata.csv: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /upload/storage/v1/b/blue_bikes_bucket/o?uploadType=resumable&upload_id=AHmUCY1BWYSqGmvv8VI1EZOwWBBdeved5BMA8hxtlgKW_IjDUFdTJ-jrKBiRVaqCTDYwfUdusP6cNvOfpdJqqP7PEtcNnDKoWWEYqAXEvmsvw99I (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_BAD_RECORD_MAC] sslv3 alert bad record mac (_ssl.c:2570)')))
[2024-11-01T18:24:19.991+0000] {logging_mixin.py:150} INFO - Error uploading /opt/***/extracted_files/202409-bluebikes-tripdata.csv: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /upload/storage/v1/b/blue_bikes_bucket/o?uploadType=resumable&upload_id=AHmUCY0sf44Tn1xDx3GHyXwkH8X7E_VckV3IQwDmIhnX8KvMFWLFiS6FohAK0RcpIndYsIGtHDhrWip638ZP6WPQIIzUeCUczm3mXDIIc-ayUvyzFw (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_BAD_RECORD_MAC] sslv3 alert bad record mac (_ssl.c:2570)')))
[2024-11-01T18:24:40.347+0000] {logging_mixin.py:150} INFO - Error uploading /opt/***/extracted_files/202409-bluebikes-tripdata.csv: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /upload/storage/v1/b/blue_bikes_bucket/o?uploadType=resumable&upload_id=AHmUCY14Q20NF3-91TueICbxWxiCBo2H3y3XnjHc-tMwI5LTyBgLxAcZUNK9RIgm0SJLuLt0dMnANQsbChdRhnIUhHVKp1JUTiWi1Oxic5hBaQwDUQ (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_BAD_RECORD_MAC] sslv3 alert bad record mac (_ssl.c:2570)')))
[2024-11-01T18:25:12.910+0000] {logging_mixin.py:150} INFO - Error uploading /opt/***/extracted_files/202409-bluebikes-tripdata.csv: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /upload/storage/v1/b/blue_bikes_bucket/o?uploadType=resumable (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xffff90da1810>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
[2024-11-01T18:25:55.276+0000] {logging_mixin.py:150} INFO - Error uploading /opt/***/extracted_files/202409-bluebikes-tripdata.csv: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /upload/storage/v1/b/blue_bikes_bucket/o?uploadType=resumable&upload_id=AHmUCY2xo0trEVwR3Ga1NRFrUfDFO00ERtV-aiCS2rvXC8S85uIKgzzkEqCBTG2XyXRl-1mxSrmTGc-hXcJtDerHpOGhO5Syyi1ivU6i5hkOvoCh6A (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_BAD_RECORD_MAC] sslv3 alert bad record mac (_ssl.c:2570)')))
[2024-11-01T18:27:01.639+0000] {logging_mixin.py:150} INFO - Error uploading /opt/***/extracted_files/202409-bluebikes-tripdata.csv: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /upload/storage/v1/b/blue_bikes_bucket/o?uploadType=resumable&upload_id=AHmUCY0Lh0qWeSOIKjP_k_qyA1ICnBsob1mo_eBIiDXnOoVsRmtOmSB_iu6RP5fqj7-09T4wO0OwXgrwdyLeiLLrwC91WDMf-6yaWphXZELHF3CCOQ (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_BAD_RECORD_MAC] sslv3 alert bad record mac (_ssl.c:2570)')))
[2024-11-01T18:32:02.278+0000] {logging_mixin.py:150} INFO - Error uploading /opt/***/extracted_files/202409-bluebikes-tripdata.csv: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /upload/storage/v1/b/blue_bikes_bucket/o?uploadType=resumable&upload_id=AHmUCY3cA09oX13jtLQIkWmj1CBbhhwvL300h8T3e3pvokd2hqBKaiwgFBtvnQsjMvOHOHhVVKT1bRdiTGQfPg3xEj60sdNpBp4uiRe1cthDTNIz (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_BAD_RECORD_MAC] sslv3 alert bad record mac (_ssl.c:2570)')))
[2024-11-01T18:36:18.535+0000] {logging_mixin.py:150} INFO - Failed to upload /opt/***/extracted_files/202409-bluebikes-tripdata.csv after 8 retries
[2024-11-01T18:36:18.761+0000] {python.py:183} INFO - Done. Returned value was: None
[2024-11-01T18:36:21.384+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=bluebikes_data_pipeline, task_id=upload_to_gcs_task, execution_date=20240901T000000, start_date=20241101T182124, end_date=20241101T183621
[2024-11-01T18:36:22.518+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2024-11-01T18:36:22.772+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
