[2024-11-01T18:24:44.196+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bluebikes_data_pipeline.upload_to_gcs_task scheduled__2024-06-01T00:00:00+00:00 [queued]>
[2024-11-01T18:24:44.279+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bluebikes_data_pipeline.upload_to_gcs_task scheduled__2024-06-01T00:00:00+00:00 [queued]>
[2024-11-01T18:24:44.281+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2024-11-01T18:24:44.400+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): upload_to_gcs_task> on 2024-06-01 00:00:00+00:00
[2024-11-01T18:24:44.840+0000] {standard_task_runner.py:57} INFO - Started process 393 to run task
[2024-11-01T18:24:44.959+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'bluebikes_data_pipeline', 'upload_to_gcs_task', 'scheduled__2024-06-01T00:00:00+00:00', '--job-id', '808', '--raw', '--subdir', 'DAGS_FOLDER/***_main.py', '--cfg-path', '/tmp/tmpo8_owhn8']
[2024-11-01T18:24:45.084+0000] {standard_task_runner.py:85} INFO - Job 808: Subtask upload_to_gcs_task
[2024-11-01T18:24:46.806+0000] {task_command.py:410} INFO - Running <TaskInstance: bluebikes_data_pipeline.upload_to_gcs_task scheduled__2024-06-01T00:00:00+00:00 [running]> on host f1ce4a924b75
[2024-11-01T18:24:48.388+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Muskan' AIRFLOW_CTX_DAG_ID='bluebikes_data_pipeline' AIRFLOW_CTX_TASK_ID='upload_to_gcs_task' AIRFLOW_CTX_EXECUTION_DATE='2024-06-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-01T00:00:00+00:00'
[2024-11-01T18:25:14.291+0000] {logging_mixin.py:150} INFO - Error uploading /opt/***/extracted_files/202406-bluebikes-tripdata.csv: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /upload/storage/v1/b/blue_bikes_bucket/o?uploadType=resumable&upload_id=AHmUCY2h-pvBjDhEHgpASNycJ9tQwKzLnrxfdbUx8Djb5qQaN1mYcEcgxo6j1kD2d9Du20zj2560qcKDMveFcNImglQ254kVM1wBDFspexAvu8Oh (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_BAD_RECORD_MAC] sslv3 alert bad record mac (_ssl.c:2570)')))
[2024-11-01T18:25:31.798+0000] {logging_mixin.py:150} INFO - Uploaded /opt/***/extracted_files/202406-bluebikes-tripdata.csv to gs://blue_bikes_bucket/202406-bluebikes-tripdata.csv
[2024-11-01T18:25:31.895+0000] {python.py:183} INFO - Done. Returned value was: None
[2024-11-01T18:25:32.605+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=bluebikes_data_pipeline, task_id=upload_to_gcs_task, execution_date=20240601T000000, start_date=20241101T182444, end_date=20241101T182532
[2024-11-01T18:25:34.477+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2024-11-01T18:25:34.894+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
